project_name = "Cardio"
current_frame = 5
screenshot_directory = "./data/screenshots"
screenshot_subdirectory_format = "%Y-%m-%d-%H-%M-%S"
rotation_factor = 3
background_r=1.0
background_g=1.0
background_b=1.0

[[meshes]]
label = "True_Lumen"
directory = "./data/seg-1-obj"
suffix = "obj"
visible = true
color_r = 0.0
color_g = 1.0
color_b = 0.0

[[meshes]]
label = "False_Lumen"
directory = "./data/seg-2-obj"
suffix = "obj"
visible = true
color_r = 1.0
color_g = 0.0
color_b = 0.0

[[volumes]]
label="Volume"
directory="./data/img-nii"
suffix="nii.gz"
visible=true
ambient=0.4
diffuse=0.6
specular=0.2
